/*
 * This header provides constants for the NUCLEI RESET
 */

#ifndef _DT_BINDINGS_NUCLEI_RESET_H
#define _DT_BINDINGS_NUCLEI_RESET_H

/* peripher */
#define NUCLEI_RESET_CTRL0_UDMA0		0
#define NUCLEI_RESET_CTRL0_UART0		1
#define NUCLEI_RESET_CTRL0_QSPI_XIP0	2
#define NUCLEI_RESET_CTRL0_QSPI1		3
#define NUCLEI_RESET_CTRL0_QSPI2		4
#define NUCLEI_RESET_CTRL0_RTC0			5
#define NUCLEI_RESET_CTRL0_I2C2ICB0		6
#define NUCLEI_RESET_CTRL0_LGPIO0		7
#define NUCLEI_RESET_CTRL0_SDIO0		8
#define NUCLEI_RESET_CTRL0_SDIO0_DMA	9
#define NUCLEI_RESET_CTRL0_DLYB_ANA0	10
#define NUCLEI_RESET_CTRL0_GMC0			11
#define NUCLEI_RESET_CTRL0_XUC0			12
#define NUCLEI_RESET_CTRL0_USB_TOP0		13
#define NUCLEI_RESET_CTRL0_XEC_GEN20	14
#define NUCLEI_RESET_CTRL0_XEC_GEN21	15
#define NUCLEI_RESET_CTRL0_DDR_TOP0		16
#define NUCLEI_RESET_CTRL0_IDU0			17
#define NUCLEI_RESET_CTRL0_IOMUX		18
#define NUCLEI_RESET_CTRL0_SAI0			19
#define NUCLEI_RESET_CTRL0_DISP0		20
#define NUCLEI_RESET_CTRL0_I2C0			21
#define NUCLEI_RESET_CTRL0_ATB2AXI0		22

#define NUCLEI_RESET_CTRL0(bit) (NUCLEI_RESET_CTRL0_##bit + (0x20 * 8))

#endif /* _DT_BINDINGS_NUCLEI_RESET_H */
