# drivers/clk/Makefile
obj-$(CONFIG_COMMON_CLK_NUCLEI) += clk-nuclei.o
clk-nuclei-y := clk-nuclei-gated-div.o \
                    clk-nuclei-mux.o \
                    clk-nuclei-pll.o \
                    clk-nuclei-core.o \
                    reset-nuclei.o
